config:
  service:
      name: jackson-api
      port: 8080
      labelName: jackson
      canaryWeight: 10
      stableWeight: 90
  appName: spring-boot-api
  enableVirtualService: true
  enableDestinationRule: true
subcomponents:
  canary:
    config:
      appName: spring-boot-api
      fullnameOverride: api-deploy-canary
  stable:
    config:
      appName: spring-boot-api
      fullnameOverride: api-deploy-stable
